routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// // Route::resource('/quiz/soal', 'QuizSoalController');
// Route::post('/quiz/{soal}', 'QuizSoalController@store')->name('quiz.soal.store');
// Route::delete('/quiz/{soal}', 'QuizSoalController@destroy')->name('soal.soal.destroy');

// Route::resource('/quiz/{quiz}/soal', 'QuizSoalController');
//
//
//





Route::group(['middleware'=>'auth'], function(){
  Route::resource('/kelas', 'KelasController');
  Route::resource('/siswa', 'SiswaController');
  Route::resource('/admin', 'AdminController');
  Route::resource('/pengajar', 'PengajarController');
  Route::resource('/matapelajaran', 'MatpelController');
  Route::resource('/matpelpengajar', 'MatpelpengajarController');
  Route::resource('/berita', 'BeritaController');
  Route::resource('/home', 'InfoController');
  Route::resource('/materi', 'MateriController');
  Route::resource('/quiz', 'QuizController');
  Route::resource('/quizsiswa/mulai/jawaban', 'JawabanController');
  Route::resource('/komen', 'KomenController');
  // Route::delete('/quiz/{soal}', 'QuizController@destroysoal');
  Route::resource('/quizz', 'MulaiQuizController');
  Route::resource('/soal', 'SoalController');
  Route::resource('/quizsiswa/mulai', 'SoalController');
  Route::resource('/quizsiswa', 'JawabanTerpilihController');
  Route::resource('/semester', 'SemesterController');
  Route::resource('/pengaturan', 'ProfileController');
  Route::resource('/hasil', 'HasilController');
  Route::get('/get_hasil/{id}', 'MakePdfController@edit');


  Route::get('/dashboard_admin', ['middleware'=>'check-permission:admin', 'uses'=>'HomeController@allAdmin']);
  Route::get('/dashboard_pengajar', ['middleware'=>'check-permission:pengajar', 'uses'=>'HomeController@allPengajar']);
  Route::get('/dashboard_siswa', ['middleware'=>'check-permission:siswa', 'uses'=>'HomeController@allSiswa']);

});

app/Materi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Kelas;
use App\MataPelajaran;
use App\User;

class materi extends Model
{
    protected $table = 'materis';

    protected $fillable = [
      'judul',
      'id_relasi',
      'nama_file',
      'id_pembuat',
      'created_at'
    ];

    public function relasi(){
    return $this->belongsTo(GuruMatpel::class,'id_relasi');
    // return $this->hasOne('nama_model','id_relasi_dari_model_yang_dituju');
  }
    public function users(){
    return $this->belongsTo(User::class,'id_pembuat');
    // return $this->hasOne('nama_model','id_relasi_dari_model_yang_dituju');
  }

}

app/Http/Controllers/MateriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Materi;
use App\MataPelajaran;
use App\GuruMatpel;
use App\Kelas;
use App\User;
use Auth;


class MateriController extends Controller
{
    /**
     * Display aa listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct()
     {
         $this->middleware('auth');
     }
    public function index()
    {
      if (checkPermission(['admin'])) {
        $gurumatpel = GuruMatpel::all();
        $kelas = Kelas::all();
        $matpel = MataPelajaran::all();
        $user = User::all();
        $materi = Materi::all();

        return view('core.materi.index', compact('materi', 'kelas', 'user', 'matpel','gurumatpel'));
      }elseif (checkPermission(['siswa'])) {
        $gurumatpel = GuruMatpel::all();
        // $kelas = Kelas::all();
        // $matpel = MataPelajaran::all();
        // $user = User::all();
        // $materi = Materi::all();
        $materi = Materi::leftJoin('guru_matpels','materis.id_relasi','=','guru_matpels.id')
                  ->leftJoin('siswas','guru_matpels.id_kelas','=','siswas.id_kelas')
                  ->where('siswas.id_users','=', Auth::user()->id)
                  ->where('guru_matpels.status','=','1')
                  ->get();


        return view('core.materi.siswa', compact('materi', 'kelas', 'user', 'matpel','gurumatpel'));
      }elseif (checkPermission(['pengajar'])) {
        $gurumatpel = GuruMatpel::where('id_guru', '=',Auth::user()->id )->get();
        $kelas = Kelas::all();
        $matpel = MataPelajaran::all();
        $user = User::all();
        $materi = Materi::whereIn('id_pembuat', [1,Auth::user()->id])->get();

        return view('core.materi.index', compact('materi', 'kelas', 'user', 'matpel','gurumatpel'));
      } else{
        echo "Null";
      }




    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      //handle upload file
      if($request->hasFile('nama_file')){
        $filenameWithExt = $request->file('nama_file')->getClientOriginalName();

        $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);

        $extension = $request->file('nama_file')->getClientOriginalExtension();
        $file_store_name = $filename.'_'.time().'.'.$extension;
        $path = $request->file('nama_file')->storeAs('public/upload_file_materi', $file_store_name);
      }else{
        $file_store_name = 'no file';
      }

      Materi::create([
       'judul' => request('judul'),
       'id_relasi' => request('idrelasi'),
       'nama_file' => $file_store_name,
       'id_pembuat' => Auth::user()->id
     ]);

     return redirect()->back()->with('alert', 'Materi Ditambahkan');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      if($request->hasFile('nama_file')){
        $filenameWithExt = $request->file('nama_file')->getClientOriginalName();

        $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);

        $extension = $request->file('nama_file')->getClientOriginalExtension();
        $file_store_name = $filename.'_'.time().'.'.$extension;
        $path = $request->file('nama_file')->storeAs('public/upload_file_materi', $file_store_name);
      }else{
        $file_store_name = $request->get('file_lama');
      }
      $materi = Materi::find($id);
      $materi->judul = $request->get('judul');
      $materi->id_relasi = $request->get('idrelasi');
      $materi->nama_file = $file_store_name;
      $materi->save();

      return redirect()->back()->with('alert', 'Materi Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $materi = Materi::find($id);
      $materi->delete();

      return redirect()->back()->with('alert','Materi Berhasil Dihapus');
    }
}

resources/views/core/materi/index.blade.php
@extends('master')
@section('title', 'Manajemen Materi')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      @if(\Session::has('alert'))
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p>{{\Session::get('alert')}}</p>
      </div>
      <br />
      @endif
      <div class="row mb-2">

        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Manajemen Materi</h1>
        </div><!-- /.col -->
        <!-- <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard v2</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Index</h3>

            <div class="card-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                  <button class="btn btn-success btn-sm" type="button" name="button" data-toggle="modal" data-target="#tambah">Tambah Materi</button>
              </div>
              <!-- MODAL TAMBAH -->
              <div id="tambah" class="modal fade" role="dialog">
                <div class="modal-dialog">

                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">Tambah Materi</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                      <form class="" action="{{route('materi.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group has-feedback">
                          <label for="">Judul</label>
                          <input type="text" name="judul" value="" class="form-control{{ $errors->has('judul') ? ' is-invalid' : '' }}" required>
                          @if ($errors->has('judul'))
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('judul') }}</strong>
                              </span>
                          @endif
                        </div>
                        <div class="form-group has-feedback">
                          <label for="kelas">Kelas & MataPelajaran</label>
                          <select class="form-control{{ $errors->has('idrelasi') ? ' is-invalid' : '' }}" name="idrelasi" id="" required>
                          
                            @foreach ($gurumatpel as $gm)
                              <option value="{{ $gm->id}}">{{ $gm->kelas->kelas}} | {{ $gm->matpel->matpel}}</option>
                            @endforeach
                          </select>

                                @if ($errors->has('idrelasi'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('idrelasi') }}</strong>
                                    </span>
                                @endif
                        </div>

                        <div class="form-group has-feedback">
                          <label for="">File</label>
                          <input type="file" name="nama_file" value="" class="form-control {{ $errors->has('file') ? ' is-invalid' : '' }}" required>
                          @if ($errors->has('file'))
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('file') }}</strong>
                              </span>
                          @endif
                        </div>
                        <div class="form-group">
                          <button type="submit" name="button" class="btn btn-info">Simpan</button>
                          <button type="button" name="button" class="btn btn-danger" data-dismiss=modal>Batal</button>
                        </div>

                      </form>
                    </div>
                    <!-- <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div> -->
                  </div>

                </div>
              </div>
              <!-- MODAL TAMBAH -->
            </div>
          </div>
          <!-- /.card-header -->
          <div class="clearfix">

          </div>
          <div class="card-body table-responsive p-3">
            <table id="example1" class="table table-hover table-bordered table-striped">
              <thead>
              <tr>
                <th>No</th>
                <th>Judul</th>
                <th>Keterangan</th>
                <th>Nama File</th>
                <th>Tanggal Posting</th>
                <th>Pembuat</th>
                <th>Aksi</th>
            </thead>
            <tbody>
              <?php $no = 0; ?>
              @foreach($materi as $m)
              <?php $no++ ?>
              <tr>
                <td>{{$no}}</td>
                <td>{{$m->judul}}</td>
                <td>{{ $m->relasi->kelas->kelas}} | {{ $m->relasi->matpel->matpel}}</td>
                <td>{{$m->nama_file}}</td>
                <td>{{ date('d F Y', strtotime($m->created_at)) }}</td>
                <td>{{$m->users->nama}}</td>
                <td>


                  <button class="btn btn-primary btn-sm" type="button" name="button" data-toggle="modal" data-target="#edit_{{$m->id}}">Ubah</button>
                  <button class="btn btn-danger btn-sm" type="button" name="button" data-toggle="modal" data-target="#delete_{{$m->id}}">Hapus</button>

                </td>
              </tr>

              <!-- MODAL EDIT -->
              <div id="edit_{{$m->id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">

                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">Ubah Materi</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                      <form class="" action="{{route('materi.update', $m->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="_method" value="PATCH">
                        <div class="form-group has-feedback">
                          <label for="">Judul</label>
                          <input type="text" name="judul" value="{{$m->judul}}" class="form-control{{ $errors->has('idrelasi') ? ' is-invalid' : '' }}" required>
                          @if ($errors->has('judul'))
                              <span class="invalid-feedback">
                                  <strong>{{ $errors->first('judul') }}</strong>
                              </span>
                          @endif
                        </div>
                        <div class="form-group has-feedback">
                          <label for="kelas">Pilih Kelas</label>
                          <select class="form-control{{ $errors->has('idrelasi') ? ' is-invalid' : '' }}" name="idrelasi" id="" required>
                            <option value="{{ $m->id_relasi}}">{{ $m->relasi->kelas->kelas}} | {{ $m->relasi->matpel->matpel}}</option>
                            @foreach ($gurumatpel as $gm)
                              <option value="{{ $gm->id}}">{{ $gm->kelas->kelas}} | {{ $gm->matpel->matpel}}</option>
                            @endforeach
                          </select>


                        </div>
                        <div class="form-group has-feedback">
                          <label for="">File</label>
                          <input type="hidden" value="{{$m->nama_file}}" name="file_lama">
                          <input type="file" name="nama_file" class="form-control{{ $errors->has('nama_file') ? ' is-invalid' : '' }}">
                          @if ($errors->has('nama_file'))
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('nama_file') }}</strong>
                              </span>
                          @endif
                        </div>
                        <div class="form-group">
                          <button type="submit" name="button" class="btn btn-success btn-sm">Simpan</button>
                          <button type="button" name="button" class="btn btn-warning btn-sm" data-dismiss=modal>Batal</button>
                        </div>
                      </form>
                    </div>
                  </div>

                </div>
              </div>
              <!-- MODAL EDIT -->
              <!-- MODAL DELETE -->
              <div id="delete_{{$m->id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">Hapus Materi</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                      <form class="" action="{{route('materi.destroy', $m->id)}}" method="post">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE">
                        <p>Yakin Anda ingin menghapus materi {{$m->judul}}</p>
                        <div class="form-group">
                          <button type="submit" name="button" class="btn btn-danger btn-sm">Hapus</button>
                          <button type="button" name="button" class="btn btn-secondary btn-sm" data-dismiss=modal>Batal</button>
                        </div>

                      </form>
                    </div>
                  </div>

                </div>
              </div>
              <!-- MODAL DELETE -->
            @endforeach
            </tbody>
            <tfoot>
              <tr>
                <th>No</th>
                <th>Judul</th>
                <th>Keterangan</th>
                <th>Nama File</th>
                <th>Tanggal Posting</th>
                <th>Pembuat</th>
                <th>Aksi</th>
              </tr>
            </tfoot>
            </table>
          </div>
          <!-- /.card-body -->

        </div>
        <!-- /.card -->
      </div>
    </div><!-- /.row -->
  </section>
  <!-- /.content -->
</div>
@endsection

resources/views/core/materi/siswa.blade.php
@extends('master')
@section('title', 'Manajemen Materi')

@section('content')
<div class="content-wrapper" style="background-image: url('dist/img/bg_out.jpg'">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      @if(\Session::has('alert'))
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p>{{\Session::get('alert')}}</p>
      </div>
      <br />
      @endif
      <div class="row mb-2">

        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Materi</h1>
        </div><!-- /.col -->
        <!-- <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard v2</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="row">
      @foreach ($materi as $key)
      <div class="col-3">
        <div class="card">
          <div class="card-header">


                <h5>{{$key->judul}}</h5>
                <hr>
                {{-- <center><a href="storage/app/public/upload_file_materi/{{$key->nama_file}}" target="_blank" class="btn btn-info"><i class="fa fa-download"></i> Download</a></center> --}}
                <center><a href="storage/app/public/upload_file_materi/{{$key->nama_file}}" target="_blank" download class="btn btn-info"><i class="fa fa-download"></i> Download</a></center>



          </div>
          <!-- /.card-header -->
          <div class="clearfix">

          </div>

          <!-- /.card-body -->

        </div>
        <!-- /.card -->
      </div>
      @endforeach
    </div><!-- /.row -->
  </section>
  <!-- /.content -->
</div>
@endsection